### ISSUE TITLE
Landing Page section 1 - Main + slideshow

### ISSUE THREAD

**Issue by Nur1995** [webAhead1/flexible#2]
Create the first section of the landing page.
Write the text "Build your own custom website with Flexible" with a "Get Started" button underneath on the left side and add a div on the right with ***automatic slideshow***** of random images.
**See Figma
Add four white circular buttons underneath that show the user that they are looping through the images. Add the ability to click on one of the white buttons to see the relevant picture

The Get Started button is an anchor link that takes the user down to the templates/questionnaire section in the landing page
Inside the slideshow, outside the images, put two arrows on either side.

**Comment by HibaAbid** [comment]
**Slider**: The slider was created (a new "_Slider_" component was added).
**Text and button**:  the text "_Build your own custom website with Flexible_" and "_Get Started_" button were added, The button is not working because we didn't build the relevant sections yet (templates/questionnaire).
**Design**: the design is not implemented yet, Asmaa is working on it.
